name: Build and Test

on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Check if go.mod or go.sum has changed
        id: check-mod-changes
        run: |
          chmod +x check-go-mod-changes.sh
          echo "::set-output name=mod_changes::$(./check-go-mod-changes.sh)"

      - name: Install dependencies
        if: steps.check-mod-changes.outputs.mod_changes == 'true'
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
